import { afterEach, describe, expect, test } from "bun:test";
import {
  mkdirSync,
  mkdtempSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import {
  ReleaseContractError,
  verifyPluginRelease,
  type VerifyPluginReleaseOptions,
  type VerifiedPluginRelease,
} from "./verify-plugin-release";

const PLUGIN_VERSION = "1.2.3";
const CLI_VERSION = "4.5.6";
const PLUGIN_TAG = `atlas--v${PLUGIN_VERSION}`;
const CLI_TAG = `atlas-cli-v${CLI_VERSION}`;
const SCRIPT = join(import.meta.dir, "verify-plugin-release.ts");
const TARGETS = [
  "atlas-darwin-arm64",
  "atlas-darwin-x64",
  "atlas-linux-arm64",
  "atlas-linux-x64",
] as const;
const DIGESTS = new Map<string, string>([
  [TARGETS[0], "1".repeat(64)],
  [TARGETS[1], "2".repeat(64)],
  [TARGETS[2], "3".repeat(64)],
  [TARGETS[3], "4".repeat(64)],
]);
const EXPECTED_ASSETS = [
  ...TARGETS,
  "checksums.txt",
  ...TARGETS.map((target) => `${target}.sigstore.json`),
];

interface ReleaseState {
  tagName: string;
  isDraft: boolean;
  isPrerelease: boolean;
  isImmutable: boolean;
}

interface TestMetadata {
  cliRelease: ReleaseState & { assets: Array<{ name: string }> };
  existingPluginRelease: ReleaseState | null;
}

interface Fixture {
  temp: string;
  root: string;
  metadataPath: string;
  releaseChecksumsPath: string;
  githubOutputPath: string;
  metadata: TestMetadata;
  options: VerifyPluginReleaseOptions;
}

const activeFixtures = new Set<string>();

afterEach(() => {
  for (const path of activeFixtures) {
    rmSync(path, { recursive: true, force: true });
  }
  activeFixtures.clear();
});

function checksumLines(
  digests: ReadonlyMap<string, string> = DIGESTS,
): string {
  return TARGETS.map((target) => `${digests.get(target)}  ${target}`).join(
    "\n",
  );
}

function writeJson(path: string, value: unknown): void {
  writeFileSync(path, `${JSON.stringify(value, null, 2)}\n`);
}

function createFixture(): Fixture {
  const temp = mkdtempSync(join(tmpdir(), "atlas-plugin-release-contract-"));
  activeFixtures.add(temp);
  const root = join(temp, "distribution");
  const manifests = [
    "atlas/.claude-plugin/plugin.json",
    "atlas/.codex-plugin/plugin.json",
    "atlas/.cursor-plugin/plugin.json",
  ];
  for (const relativePath of manifests) {
    const path = join(root, relativePath);
    mkdirSync(join(path, ".."), { recursive: true });
    writeJson(path, { name: "atlas", version: PLUGIN_VERSION });
  }
  mkdirSync(join(root, "atlas/bin"), { recursive: true });
  writeFileSync(join(root, "atlas/bin/cli-version"), `${CLI_VERSION}\n`);
  writeJson(join(root, "atlas/bin/cli-pin-policy.json"), {
    schemaVersion: 1,
    state: "pinned",
  });
  writeFileSync(
    join(root, "atlas/bin/cli-checksums"),
    [
      "# cli-checksums",
      `# Generated by the Atlas CLI release workflow for version ${CLI_VERSION}.`,
      checksumLines(),
      "",
    ].join("\n"),
  );

  const metadataPath = join(temp, "release-metadata.json");
  const releaseChecksumsPath = join(temp, "checksums.txt");
  const githubOutputPath = join(temp, "github-output");
  const metadata: TestMetadata = {
    cliRelease: {
      tagName: CLI_TAG,
      isDraft: false,
      isPrerelease: false,
      isImmutable: true,
      assets: EXPECTED_ASSETS.map((name) => ({ name })),
    },
    existingPluginRelease: null,
  };
  writeFileSync(releaseChecksumsPath, `${checksumLines()}\n`);
  writeJson(metadataPath, metadata);

  return {
    temp,
    root,
    metadataPath,
    releaseChecksumsPath,
    githubOutputPath,
    metadata,
    options: {
      root,
      tag: PLUGIN_TAG,
      metadataPath,
      releaseChecksumsPath,
      githubOutputPath,
    },
  };
}

function runFixture(fixture: Fixture): VerifiedPluginRelease {
  writeJson(fixture.metadataPath, fixture.metadata);
  return verifyPluginRelease(fixture.options);
}

function captureContractError(action: () => unknown): ReleaseContractError {
  try {
    action();
  } catch (error) {
    if (error instanceof ReleaseContractError) return error;
    throw error;
  }
  throw new Error("expected the release verifier to fail");
}

function expectFailure(
  fixture: Fixture,
  code: string,
  options: VerifyPluginReleaseOptions = fixture.options,
): ReleaseContractError {
  writeJson(fixture.metadataPath, fixture.metadata);
  const error = captureContractError(() => verifyPluginRelease(options));
  expect(error.code).toBe(code);
  expect(error.message).not.toContain("\n    at ");
  return error;
}

describe("valid release pairs", () => {
  test("accepts a new immutable plugin release and writes stable outputs", () => {
    const fixture = createFixture();
    expect(runFixture(fixture)).toEqual({
      releaseMode: "create",
      pluginVersion: PLUGIN_VERSION,
      cliVersion: CLI_VERSION,
      pluginReleaseTag: PLUGIN_TAG,
      cliReleaseTag: CLI_TAG,
    });
    expect(readFileSync(fixture.githubOutputPath, "utf8")).toBe(
      [
        "release_mode=create",
        `plugin_version=${PLUGIN_VERSION}`,
        `cli_version=${CLI_VERSION}`,
        `plugin_release_tag=${PLUGIN_TAG}`,
        `cli_release_tag=${CLI_TAG}`,
        "",
      ].join("\n"),
    );
  });

  test("accepts an exact immutable existing release as a resumable retry", () => {
    const fixture = createFixture();
    fixture.metadata.existingPluginRelease = {
      tagName: PLUGIN_TAG,
      isDraft: false,
      isPrerelease: false,
      isImmutable: true,
    };
    expect(runFixture(fixture).releaseMode).toBe("resume");
  });
});

describe("plugin tag and manifest contract", () => {
  for (const tag of [
    "v1.2.3",
    "atlas-v1.2.3",
    "atlas--v01.2.3",
    "atlas--v1.2.3-rc.1",
    "atlas--v1.2",
  ]) {
    test(`rejects malformed native tag ${tag}`, () => {
      const fixture = createFixture();
      expectFailure(fixture, "invalid_plugin_release_tag", {
        ...fixture.options,
        tag,
      });
    });
  }

  test("rejects a tag whose version differs from the manifests", () => {
    const fixture = createFixture();
    expectFailure(fixture, "plugin_tag_version_mismatch", {
      ...fixture.options,
      tag: "atlas--v1.2.4",
    });
  });

  test("rejects malformed manifest JSON", () => {
    const fixture = createFixture();
    writeFileSync(
      join(fixture.root, "atlas/.claude-plugin/plugin.json"),
      "{broken",
    );
    expectFailure(fixture, "invalid_json");
  });

  test("rejects a non-string manifest version", () => {
    const fixture = createFixture();
    writeJson(join(fixture.root, "atlas/.claude-plugin/plugin.json"), {
      version: 123,
    });
    expectFailure(fixture, "invalid_metadata_type");
  });

  test("rejects version drift among plugin manifests", () => {
    const fixture = createFixture();
    writeJson(join(fixture.root, "atlas/.cursor-plugin/plugin.json"), {
      version: "1.2.4",
    });
    expectFailure(fixture, "plugin_manifest_version_drift");
  });

  test("rejects a missing manifest without exposing a filesystem exception", () => {
    const fixture = createFixture();
    rmSync(join(fixture.root, "atlas/.codex-plugin/plugin.json"));
    const error = expectFailure(fixture, "input_file_unavailable");
    expect(error.message).not.toContain(fixture.temp);
  });
});

describe("local and remote checksum contract", () => {
  test("rejects bootstrap policy even if digest-shaped content exists", () => {
    const fixture = createFixture();
    writeJson(join(fixture.root, "atlas/bin/cli-pin-policy.json"), {
      schemaVersion: 1,
      state: "bootstrap",
    });
    expectFailure(fixture, "bootstrap_cli_pin_policy");
  });

  test("rejects malformed or extensible-looking pin policy state", () => {
    const fixture = createFixture();
    writeJson(join(fixture.root, "atlas/bin/cli-pin-policy.json"), {
      schemaVersion: 1,
      state: "pinned",
      allowPlaceholder: true,
    });
    expectFailure(fixture, "invalid_cli_pin_policy");
  });

  test("rejects pre-release placeholder pins", () => {
    const fixture = createFixture();
    writeFileSync(
      join(fixture.root, "atlas/bin/cli-checksums"),
      "# TODO(release): no immutable CLI release yet\n",
    );
    expectFailure(fixture, "placeholder_cli_pins");
  });

  test("rejects a missing generated-version header", () => {
    const fixture = createFixture();
    writeFileSync(
      join(fixture.root, "atlas/bin/cli-checksums"),
      `${checksumLines()}\n`,
    );
    expectFailure(fixture, "generated_pin_header_count");
  });

  test("rejects duplicate generated-version headers", () => {
    const fixture = createFixture();
    const path = join(fixture.root, "atlas/bin/cli-checksums");
    writeFileSync(
      path,
      `${readFileSync(path, "utf8")}# Generated twice for version ${CLI_VERSION}.\n`,
    );
    expectFailure(fixture, "generated_pin_header_count");
  });

  test("rejects pins generated for a different CLI version", () => {
    const fixture = createFixture();
    const path = join(fixture.root, "atlas/bin/cli-checksums");
    writeFileSync(
      path,
      readFileSync(path, "utf8").replace(
        `version ${CLI_VERSION}.`,
        "version 4.5.7.",
      ),
    );
    expectFailure(fixture, "generated_pin_version_mismatch");
  });

  test("rejects a partial local pin set", () => {
    const fixture = createFixture();
    const path = join(fixture.root, "atlas/bin/cli-checksums");
    writeFileSync(
      path,
      [
        `# Generated by workflow for version ${CLI_VERSION}.`,
        checksumLines().split("\n").slice(0, 3).join("\n"),
        "",
      ].join("\n"),
    );
    expectFailure(fixture, "missing_checksum_target");
  });

  test("rejects a duplicate local pin", () => {
    const fixture = createFixture();
    const path = join(fixture.root, "atlas/bin/cli-checksums");
    writeFileSync(
      path,
      `${readFileSync(path, "utf8")}${DIGESTS.get(TARGETS[0])}  ${TARGETS[0]}\n`,
    );
    expectFailure(fixture, "duplicate_checksum_target");
  });

  test("rejects malformed local pin syntax", () => {
    const fixture = createFixture();
    const path = join(fixture.root, "atlas/bin/cli-checksums");
    writeFileSync(
      path,
      readFileSync(path, "utf8").replace("1".repeat(64), "A".repeat(64)),
    );
    expectFailure(fixture, "malformed_checksum_line");
  });

  test("rejects an all-zero local digest", () => {
    const fixture = createFixture();
    const path = join(fixture.root, "atlas/bin/cli-checksums");
    writeFileSync(
      path,
      readFileSync(path, "utf8").replace("1".repeat(64), "0".repeat(64)),
    );
    expectFailure(fixture, "zero_checksum_digest");
  });

  test("rejects a downloaded checksum mismatch", () => {
    const fixture = createFixture();
    writeFileSync(
      fixture.releaseChecksumsPath,
      `${checksumLines().replace("1".repeat(64), "f".repeat(64))}\n`,
    );
    expectFailure(fixture, "cli_checksum_mismatch");
  });

  test("rejects comments in the downloaded release checksum file", () => {
    const fixture = createFixture();
    writeFileSync(
      fixture.releaseChecksumsPath,
      `# not part of the immutable checksum contract\n${checksumLines()}\n`,
    );
    expectFailure(fixture, "unexpected_checksum_comment");
  });

  test("rejects a partial downloaded checksum set", () => {
    const fixture = createFixture();
    writeFileSync(
      fixture.releaseChecksumsPath,
      `${checksumLines().split("\n").slice(0, 3).join("\n")}\n`,
    );
    expectFailure(fixture, "missing_checksum_target");
  });

  test("rejects duplicate downloaded checksum targets", () => {
    const fixture = createFixture();
    writeFileSync(
      fixture.releaseChecksumsPath,
      `${checksumLines()}\n${DIGESTS.get(TARGETS[0])}  ${TARGETS[0]}\n`,
    );
    expectFailure(fixture, "duplicate_checksum_target");
  });

  test("rejects an unsupported downloaded checksum target", () => {
    const fixture = createFixture();
    writeFileSync(
      fixture.releaseChecksumsPath,
      `${checksumLines()}\n${"5".repeat(64)}  atlas-windows-x64\n`,
    );
    expectFailure(fixture, "malformed_checksum_line");
  });

  test("bounds checksum input size before parsing", () => {
    const fixture = createFixture();
    writeFileSync(fixture.releaseChecksumsPath, "x".repeat(64_001));
    expectFailure(fixture, "input_file_too_large");
  });
});

describe("normalized GitHub metadata boundary", () => {
  test("rejects malformed metadata JSON", () => {
    const fixture = createFixture();
    writeFileSync(fixture.metadataPath, "{not-json");
    const error = captureContractError(() =>
      verifyPluginRelease(fixture.options),
    );
    expect(error.code).toBe("invalid_json");
  });

  test("bounds metadata input size before JSON parsing", () => {
    const fixture = createFixture();
    writeFileSync(fixture.metadataPath, " ".repeat(1_000_001));
    const error = captureContractError(() =>
      verifyPluginRelease(fixture.options),
    );
    expect(error.code).toBe("input_file_too_large");
  });

  test("rejects a missing top-level field", () => {
    const fixture = createFixture();
    writeJson(fixture.metadataPath, { cliRelease: fixture.metadata.cliRelease });
    const error = captureContractError(() =>
      verifyPluginRelease(fixture.options),
    );
    expect(error.code).toBe("missing_metadata_field");
  });

  test("rejects unknown top-level fields with bounded diagnostics", () => {
    const fixture = createFixture();
    const longKey = `unexpected-${"x".repeat(1_000)}`;
    writeJson(fixture.metadataPath, {
      ...fixture.metadata,
      [longKey]: true,
    });
    const error = captureContractError(() =>
      verifyPluginRelease(fixture.options),
    );
    expect(error.code).toBe("unknown_metadata_field");
    expect(error.message.length).toBeLessThan(400);
    expect(error.message).not.toContain(longKey);
  });

  test("rejects a non-object CLI release", () => {
    const fixture = createFixture();
    writeJson(fixture.metadataPath, {
      cliRelease: null,
      existingPluginRelease: null,
    });
    const error = captureContractError(() =>
      verifyPluginRelease(fixture.options),
    );
    expect(error.code).toBe("invalid_metadata_shape");
  });

  test("rejects unknown CLI release fields", () => {
    const fixture = createFixture();
    writeJson(fixture.metadataPath, {
      ...fixture.metadata,
      cliRelease: {
        ...fixture.metadata.cliRelease,
        htmlUrl: "https://example.invalid",
      },
    });
    const error = captureContractError(() =>
      verifyPluginRelease(fixture.options),
    );
    expect(error.code).toBe("unknown_metadata_field");
  });

  test("rejects non-boolean release state", () => {
    const fixture = createFixture();
    writeJson(fixture.metadataPath, {
      ...fixture.metadata,
      cliRelease: {
        ...fixture.metadata.cliRelease,
        isImmutable: "true",
      },
    });
    const error = captureContractError(() =>
      verifyPluginRelease(fixture.options),
    );
    expect(error.code).toBe("invalid_metadata_type");
  });

  test("rejects a non-array asset list", () => {
    const fixture = createFixture();
    writeJson(fixture.metadataPath, {
      ...fixture.metadata,
      cliRelease: {
        ...fixture.metadata.cliRelease,
        assets: "atlas-darwin-arm64",
      },
    });
    const error = captureContractError(() =>
      verifyPluginRelease(fixture.options),
    );
    expect(error.code).toBe("invalid_metadata_type");
  });

  test("rejects too many assets before iterating the list", () => {
    const fixture = createFixture();
    fixture.metadata.cliRelease.assets = Array.from(
      { length: 33 },
      (_, index) => ({ name: `asset-${index}` }),
    );
    expectFailure(fixture, "too_many_release_assets");
  });

  test("rejects malformed asset entries", () => {
    const fixture = createFixture();
    writeJson(fixture.metadataPath, {
      ...fixture.metadata,
      cliRelease: {
        ...fixture.metadata.cliRelease,
        assets: [{ name: TARGETS[0], size: 123 }],
      },
    });
    const error = captureContractError(() =>
      verifyPluginRelease(fixture.options),
    );
    expect(error.code).toBe("unknown_metadata_field");
  });
});

describe("immutable CLI release contract", () => {
  const releaseStateCases: Array<{
    name: string;
    mutate: (state: TestMetadata["cliRelease"]) => void;
    code: string;
  }> = [
    {
      name: "wrong CLI release tag",
      mutate: (state) => {
        state.tagName = "atlas-cli-v4.5.7";
      },
      code: "release_tag_mismatch",
    },
    {
      name: "draft CLI release",
      mutate: (state) => {
        state.isDraft = true;
      },
      code: "draft_release",
    },
    {
      name: "prerelease CLI release",
      mutate: (state) => {
        state.isPrerelease = true;
      },
      code: "prerelease_release",
    },
    {
      name: "mutable CLI release",
      mutate: (state) => {
        state.isImmutable = false;
      },
      code: "mutable_release",
    },
  ];

  for (const releaseCase of releaseStateCases) {
    test(`rejects ${releaseCase.name}`, () => {
      const fixture = createFixture();
      releaseCase.mutate(fixture.metadata.cliRelease);
      expectFailure(fixture, releaseCase.code);
    });
  }

  test("rejects a missing required CLI asset", () => {
    const fixture = createFixture();
    fixture.metadata.cliRelease.assets.pop();
    expectFailure(fixture, "missing_cli_release_asset");
  });

  test("rejects an unsupported CLI asset", () => {
    const fixture = createFixture();
    fixture.metadata.cliRelease.assets.push({ name: "source.zip" });
    expectFailure(fixture, "unexpected_cli_release_asset");
  });

  test("rejects a duplicate CLI asset", () => {
    const fixture = createFixture();
    fixture.metadata.cliRelease.assets.push({ name: TARGETS[0] });
    expectFailure(fixture, "duplicate_cli_release_asset");
  });
});

describe("existing plugin release retry contract", () => {
  const existingReleaseCases: Array<{
    name: string;
    state: ReleaseState;
    code: string;
  }> = [
    {
      name: "different tag",
      state: {
        tagName: "atlas--v1.2.2",
        isDraft: false,
        isPrerelease: false,
        isImmutable: true,
      },
      code: "release_tag_mismatch",
    },
    {
      name: "draft state",
      state: {
        tagName: PLUGIN_TAG,
        isDraft: true,
        isPrerelease: false,
        isImmutable: true,
      },
      code: "draft_release",
    },
    {
      name: "prerelease state",
      state: {
        tagName: PLUGIN_TAG,
        isDraft: false,
        isPrerelease: true,
        isImmutable: true,
      },
      code: "prerelease_release",
    },
    {
      name: "mutable state",
      state: {
        tagName: PLUGIN_TAG,
        isDraft: false,
        isPrerelease: false,
        isImmutable: false,
      },
      code: "mutable_release",
    },
  ];

  for (const releaseCase of existingReleaseCases) {
    test(`rejects an existing plugin release with ${releaseCase.name}`, () => {
      const fixture = createFixture();
      fixture.metadata.existingPluginRelease = releaseCase.state;
      expectFailure(fixture, releaseCase.code);
    });
  }

  test("rejects unknown existing-release fields", () => {
    const fixture = createFixture();
    writeJson(fixture.metadataPath, {
      ...fixture.metadata,
      existingPluginRelease: {
        tagName: PLUGIN_TAG,
        isDraft: false,
        isPrerelease: false,
        isImmutable: true,
        assets: [],
      },
    });
    const error = captureContractError(() =>
      verifyPluginRelease(fixture.options),
    );
    expect(error.code).toBe("unknown_metadata_field");
  });
});

describe("command-line boundary", () => {
  test("prints help without reading release inputs", () => {
    const result = Bun.spawnSync(["bun", SCRIPT, "--help"], {
      stdout: "pipe",
      stderr: "pipe",
    });
    expect(result.exitCode).toBe(0);
    expect(result.stdout.toString()).toContain("--release-checksums");
    expect(result.stderr.toString()).toBe("");
  });

  test("fails closed on an unknown argument", () => {
    const result = Bun.spawnSync(["bun", SCRIPT, "--surprise", "value"], {
      stdout: "pipe",
      stderr: "pipe",
    });
    expect(result.exitCode).toBe(1);
    expect(result.stderr.toString()).toContain("[unknown_argument]");
    expect(result.stderr.toString()).not.toContain("\n    at ");
  });

  test("fails closed on a missing required argument", () => {
    const result = Bun.spawnSync(
      [
        "bun",
        SCRIPT,
        "--root",
        ".",
        "--tag",
        PLUGIN_TAG,
        "--metadata",
        "metadata.json",
      ],
      { stdout: "pipe", stderr: "pipe" },
    );
    expect(result.exitCode).toBe(1);
    expect(result.stderr.toString()).toContain(
      "[missing_argument] --release-checksums is required",
    );
    expect(result.stderr.toString()).not.toContain("\n    at ");
  });

  test("rejects an explicitly empty GitHub output path", () => {
    const result = Bun.spawnSync(
      [
        "bun",
        SCRIPT,
        "--root",
        ".",
        "--tag",
        PLUGIN_TAG,
        "--metadata",
        "metadata.json",
        "--release-checksums",
        "checksums.txt",
        "--github-output",
        "",
      ],
      { stdout: "pipe", stderr: "pipe" },
    );
    expect(result.exitCode).toBe(1);
    expect(result.stderr.toString()).toContain(
      "[missing_argument_value] --github-output requires a value",
    );
  });
});
